# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    app.show_user_listener.class: AppBundle\EventListener\MyShowUserListener
    app.menu_listener.class: AppBundle\EventListener\MyMenuItemListener
    security.authentication_handler.class: AppBundle\EventListener\AuthenticationHandler

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.security_access_handler:
        class: AppBundle\EventListener\AppSecurityAccessHandler
        tags:
           - { name: kernel.event_listener, event: security.kernel_response, method: handle }

    app.show_user_listener:
        class: %app.show_user_listener.class%
        arguments: ['@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }

    app.menu_listener:
        class: %app.menu_listener.class%
        arguments: ['@security.token_storage', '@security.authorization_checker']
        tags:
            - { name: kernel.event_listener, event: theme.sidebar_setup_menu, method:onSetupMenu }

    security.authentication.handler:
        class:  %security.authentication_handler.class%
        arguments:  ['@doctrine.orm.entity_manager', '@request_stack', '@security.token_storage']
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    security.webservice_user_provider:
        class: AppBundle\Security\WebServiceUserProvider
        arguments:  ['@doctrine.orm.entity_manager']
