homepage:
  path: /
  defaults: {_controller: AppBundle:Default:index}

security_login:
  path: /login
  defaults: {_controller: AppBundle:Security:login}

avanzu_admin_logout:
  path: /logout

avanzu_admin_profile:
    path: /profile/{userid}/
    defaults: {_controller: AppBundle:Profile:user}


avanzu_menu_test:
    path: /test_menu/
    defaults: {_controller: AvanzuAdminThemeBundle:Sidebar:menu}